ci: fix gcc not understanding array is not dynamic
Use alloca() to continue to allocate on stack. This requires alloca() to
be supported by compiler.

Issue fixed at gcc v13.1+.
Tested gcc versions:
  - 11.2, 11.3, 11.4
  - 12.1, 12.2, 12.3, 12.4
  - 13.1

../src/main.c: In function ‘main’:
../src/main.c:277:10: error: variable-sized object may not be initialized
  277 |   struct gamepad gamepads[maxSupportedControllers] = {};
      |          ^~~~~~~